name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Add Webasm target
      run: rustup target add wasm32-unknown-unknown
    - name: Build Webasm
      run: cargo build --target wasm32-unknown-unknown --release --verbose
    - name: Store Webasm artifact
      uses: actions/upload-artifact@v4
      with:
        name: artifact
        path: ./target/wasm32-unknown-unknown/release/snake_clone.wasm
